-- Run this once against ev_database ONLY IF the old enum-typed schema was already applied.
-- Safe to run even if nothing exists yet (IF EXISTS everywhere). No data will be lost - DB is empty.

DROP TABLE IF EXISTS "CAR" CASCADE;
DROP TABLE IF EXISTS "NOTICE" CASCADE;
DROP TABLE IF EXISTS "NOTICE_ATTACHMENT" CASCADE;
DROP TABLE IF EXISTS "BATCH_JOB_LOGS" CASCADE;
DROP TABLE IF EXISTS "AI_REPORTS" CASCADE;
DROP TABLE IF EXISTS "TERM_AGREEMENT" CASCADE;
DROP TABLE IF EXISTS "BATTERY_OFFERS" CASCADE;
DROP TABLE IF EXISTS "CHARGER" CASCADE;
DROP TABLE IF EXISTS "CHARGING_STATION" CASCADE;
DROP TABLE IF EXISTS "BATTERY_PASSPORT" CASCADE;
DROP TABLE IF EXISTS "BATTERY_PROPOSALS" CASCADE;
DROP TABLE IF EXISTS "EXTERNAL_INTEGRATIONS" CASCADE;
DROP TABLE IF EXISTS "USER" CASCADE;
DROP TABLE IF EXISTS "ACTION_LOGS" CASCADE;
DROP TABLE IF EXISTS "NOTIFICATION_MATRIX" CASCADE;
DROP TABLE IF EXISTS "CHARGING_SESSION" CASCADE;
DROP TABLE IF EXISTS "NOTIFICATIONS" CASCADE;
DROP TABLE IF EXISTS "TWIN_FRAMES" CASCADE;
DROP TABLE IF EXISTS "BATTERY_DIAGNOSIS_METRICS" CASCADE;
DROP TABLE IF EXISTS "BATCH_JOBS" CASCADE;
DROP TABLE IF EXISTS "LOGIN_LOGS" CASCADE;
DROP TABLE IF EXISTS "BATTERY_SOH_HISTORY" CASCADE;
DROP TABLE IF EXISTS "ANOMALY_LOGS" CASCADE;
DROP TABLE IF EXISTS "NOTIFICATION_CHANNELS" CASCADE;

DROP TYPE IF EXISTS "risk_level_enum" CASCADE;
DROP TYPE IF EXISTS "login_status_enum" CASCADE;
DROP TYPE IF EXISTS "batch_job_status_enum" CASCADE;
DROP TYPE IF EXISTS "charging_state_enum" CASCADE;
DROP TYPE IF EXISTS "user_role_enum" CASCADE;
DROP TYPE IF EXISTS "charger_type_enum" CASCADE;
DROP TYPE IF EXISTS "charger_status_enum" CASCADE;
DROP TYPE IF EXISTS "report_type_enum" CASCADE;
DROP TYPE IF EXISTS "batch_run_type_enum" CASCADE;
DROP TYPE IF EXISTS "battery_level_enum" CASCADE;
