ALTER TABLE "EXTERNAL_INTEGRATIONS" ADD COLUMN IF NOT EXISTS "is_status" BOOLEAN DEFAULT TRUE NOT NULL;
ALTER TABLE "EXTERNAL_INTEGRATIONS" ADD COLUMN IF NOT EXISTS "last_connected_at" TIMESTAMPTZ;
ALTER TABLE "EXTERNAL_INTEGRATIONS" ADD COLUMN IF NOT EXISTS "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP;
